### ISSUE TITLE
Computing voting breakdowns

### ISSUE THREAD

**Issue by eonwarped** [steem-engine-exchange/nitrous#25]
@passionbull Gathering all the references here since it was being discussed in various places that are now closed.

This has what the computation is supposed to look like, towards the end, but it didn't get put in:
https://github.com/steem-engine-exchange/nitrous/pull/12#issuecomment-503598550

This shows how to pull from scot settings: https://github.com/steem-engine-exchange/nitrous/pull/24#issuecomment-504485022

Earlier with the last link I thought we were just talking about computing the estimate of the full post, not the breakdown, so the link I provided was for that, but not for breakdowns.

**Comment by passionbull** [comment]
Thank you for gathering discussion.

In https://github.com/steem-engine-exchange/nitrous/pull/24#issuecomment-504648011, 
he said sum of calcualted voting value is different from payout.
Could you check this?

**Comment by eonwarped** [comment]
Addressed by https://github.com/steem-engine-exchange/nitrous/commit/4e0dd64331a64c962180743d946b0c1a6d93d460
