### ISSUE TITLE
5 Very-Simple Tasks For Scotty-Marlians - Change Metadata, Add Label For 'Certified Uloggers', Add A New Menu Tab etc.

### ISSUE THREAD

**Issue by surpassinggoogle** [steem-engine-exchange/nitrous#50]
#### Task 1:
Change metadata for marlians.com. This is the aspect of marlians.com that forms the synopsis introducing marlians.com in the search engine and enhances SEO. We would like it to be this:

**Marlians.com is a social media platform that rewards you becoming 'confirm naijan'. There is 'naijan' and there is 'confirm naijan' and while one is regular, the other is 'great'. There is a "Naira Marley" and there is a "Bob Marley", then there is the likes of "Fela" & "Mohammed Ali". Now, there is also "you". 
Be 'confirm naijan'; be great; get rewarded!
You get rewarded in 'MARLIANS', a digital currency that attempts to reward 'greatness'. 'Greatness' being a by-product of 'evolving the human'.** 

#### Task 2:
Allow for 12 tags - We want users to be able to insert up to 12-tags beneath their post instead of just 5-tags.

#### Task 3: 
Add label for 'certified uloggers' - We would like all certified uloggers to have a label "Certified Ulogger" attached to their profile, **similar to this:**
![image](https://user-images.githubusercontent.com/23729959/61671122-d2dc8b00-ad18-11e9-9402-a12f6fb7a2d2.png)
![image](https://user-images.githubusercontent.com/23729959/61710901-52a03f00-ad85-11e9-8850-a5631bc319a9.png)

> Our list of certified uloggers is a dynamic list that updates as 'users are followed/unfollowed by the @uloggers account on steem' and it is seen here: https://steemit.com/@uloggers/followed

#### Task 4:
We would like to add one more tab to the top-right menu labeled "Vote steemgigs" that links to this steemconnect URL: https://app.steemconnect.com/sign/account-witness-vote?witness=steemgigs&approve=1

#### Task 5:
Add a _'posted via https://marlians.com'_ alert to the bottom of posts and comments made via marlians.com that is visible from all other steem condensers.
> For comment alert, kindly make font size smaller than the 'actual comment font-size'.

**Comment by eonwarped** [comment]
I did most of these already. Though it's 10, not 12 tags already. If you insist on 12 I can put it there but for now i'm matching it across all nitrous instances.
